
$scriptblock = {  
  

    cls
    $teamsexe = ($home + '\downloads\Teams_windows_x64.1.4.00.1973.exe')

    start-job -Name dlteams -ScriptBlock { 
        if ( -Not (test-path ($using:teamsexe)))
        {
            write-host start dl teams

            #$url = 'https://go.microsoft.com/fwlink/p/?LinkID=869426&clcid=0x1009&culture=en-ca&country=CA&lm=deeplink&lmsrc=groupChatMarketingPageWeb&cmpid=directDownloadWin64'

            $url = 'https://statics.teams.cdn.office.net/production-windows-x64/1.4.00.1973/Teams_windows_x64.exe'

            (New-Object System.Net.WebClient).DownloadFile($url  , $using:teamsexe )
        }
    }


    if (test-path C:\Users\*\AppData\Local\Microsoft\Teams\current\Teams.exe)
    {
        kill -name teams -force

        write-host ===========================
        write-host uninstall teams
        write-host ===========================

        (Get-ItemProperty C:\Users\*\AppData\Local\Microsoft\Teams\Current).PSParentPath | foreach-object {Start-Process $_\Update.exe -ArgumentList "--uninstall /s" -Wait}
    }

    Remove-Item -Recurse -force C:\Users\garjo3\AppData\Local\Microsoft\Teams
    Remove-Item -Recurse -force C:\Users\garjo3\AppData\Roaming\Microsoft\Teams
    Remove-Item -Recurse -force C:\Users\garjo3\AppData\Roaming\Teams
    Remove-Item -Recurse -force C:\windows\Prefetch\TEAMS*.*
    Remove-Item -Recurse -force $env:LOCALAPPDATA\Microsoft\Teams\

    write-host ===========================
    write-host uninstalled teams
    write-host ===========================

    write-host ===========================
    write-host wait for download to finish
    write-host ===========================

    $time = 0

    do{
        Write-Host wait for $teamsexe to exist $time sec elapsed
                    $time++
                    sleep -Seconds 1
    }while( -Not (test-path ($teamsexe)))



    do{
                Write-Host((Get-Item $teamsexe).length/1MB) MB
                $time++
                sleep -Seconds 1
                write-host wait for dlteams to finish $time sec elapsed               
    }while((Get-job -Name dlteams | where state -eq Running) -and ($Time -lt 120))

    Get-Job  -Name dlteams | Wait-Job
    remove-Job -Name dlteams


    write-host ===========================
    write-host Starting teams install
    write-host ===========================

    Start-Sleep -s 1


    $teamsexe = ($home + '\downloads\Teams_windows_x64.1.4.00.1973.exe')
    Start-Process $teamsexe

    $isVPN = ipconfig /all

    if ($isVPN -match "Juniper Networks Virtual Adapter")
    {

    
    }
    else
    {
        TASKKILL /F /IM pulse.exe
        Write-Host Not Connected : Juniper Networks Virtual Adapter 
        #start-process "C:\Program Files (x86)\Common Files\Pulse Secure\JamUI\Pulse.exe" -show
        Start-Process "C:\Program Files (x86)\Common Files\Pulse Secure\JamUI\Pulse.exe" -ArgumentList "-show"
    }



}
$encoded = [convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($scriptblock))
$batfile = ($home + '\Desktop\reset-teams.bat')
remove-item $batfile

$cmdcode = ('powershell.exe -NoProfile -EncodedCommand '+$encoded)
$cmdcode | Out-File -encoding "ASCII" -filePath $batfile
#Start-Process 'cmd' -ArgumentList "/k powershell.exe -NoProfile -EncodedCommand $encoded"
Start-Process 'cmd' -ArgumentList "/k $batfile"


#powershell.exe -NoProfile -EncodedCommand IAAgAA0ACgBzAHQAbwBwAC0AagBvAGIAIAAtAE4AYQBtAGUAIABkAGwAdABlAGEAbQBzAA0ACgByAGUAbQBvAHYAZQAtAGoAbwBiACAALQBOAGEAbQBlACAAZABsAHQAZQBhAG0AcwANAAoAcwB0AGEAcgB0AC0AagBvAGIAIAAtAE4AYQBtAGUAIABkAGwAdABlAGEAbQBzACAALQBTAGMAcgBpAHAAdABCAGwAbwBjAGsAIAB7ACAADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAdABlAGEAbQBzAGUAeABlACAAPQAgACgAJABoAG8AbQBlACAAKwAgACcAXABkAG8AdwBuAGwAbwBhAGQAcwBcAFQAZQBhAG0AcwBfAHcAaQBuAGQAbwB3AHMAXwB4ADYANAAuAGUAeABlACcAKQANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAcgBlAG0AbwB2AGUALQBpAHQAZQBtACAAJAB0AGUAYQBtAHMAZQB4AGUADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAGkAZgAgACgAIAAtAE4AbwB0ACAAKAB0AGUAcwB0AC0AcABhAHQAaAAgACgAJAB0AGUAYQBtAHMAZQB4AGUAKQApACkADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAHsADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAdwByAGkAdABlAC0AaABvAHMAdAAgAGQAbAAgAHQAZQBhAG0AcwANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAHUAcgBsACAAPQAgACcAaAB0AHQAcABzADoALwAvAGcAbwAuAG0AaQBjAHIAbwBzAG8AZgB0AC4AYwBvAG0ALwBmAHcAbABpAG4AawAvAHAALwA/AEwAaQBuAGsASQBEAD0AOAA2ADkANAAyADYAJgBjAGwAYwBpAGQAPQAwAHgAMQAwADAAOQAmAGMAdQBsAHQAdQByAGUAPQBlAG4ALQBjAGEAJgBjAG8AdQBuAHQAcgB5AD0AQwBBACYAbABtAD0AZABlAGUAcABsAGkAbgBrACYAbABtAHMAcgBjAD0AZwByAG8AdQBwAEMAaABhAHQATQBhAHIAawBlAHQAaQBuAGcAUABhAGcAZQBXAGUAYgAmAGMAbQBwAGkAZAA9AGQAaQByAGUAYwB0AEQAbwB3AG4AbABvAGEAZABXAGkAbgA2ADQAJwANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAjACgATgBlAHcALQBPAGIAagBlAGMAdAAgAFMAeQBzAHQAZQBtAC4ATgBlAHQALgBXAGUAYgBDAGwAaQBlAG4AdAApAC4ARABvAHcAbgBsAG8AYQBkAEYAaQBsAGUAKAAkAHUAcgBsACAAIAAsACAAJAB0AGUAYQBtAHMAZQB4AGUAIAApAA0ACgANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAHcAYwAgAD0AIABOAGUAdwAtAE8AYgBqAGUAYwB0ACAAUwB5AHMAdABlAG0ALgBOAGUAdAAuAFcAZQBiAEMAbABpAGUAbgB0ACAAIAANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAjAFIAZQBnAGkAcwB0AGUAcgAtAE8AYgBqAGUAYwB0AEUAdgBlAG4AdAAgAC0ASQBuAHAAdQB0AE8AYgBqAGUAYwB0ACAAJAB3AGMAIAAtAEUAdgBlAG4AdABOAGEAbQBlACAARABvAHcAbgBsAG8AYQBkAFAAcgBvAGcAcgBlAHMAcwBDAGgAYQBuAGcAZQBkACAALQBTAG8AdQByAGMAZQBJAGQAZQBuAHQAaQBmAGkAZQByACAAVwBlAGIAQwBsAGkAZQBuAHQALgBEAG8AdwBuAGwAbwBhAGQAUAByAG8AZwByAGUAcwBzAEMAaABhAG4AZwBlAGQAIAAtAEEAYwB0AGkAbwBuACAAewAgAFcAcgBpAHQAZQAtAFAAcgBvAGcAcgBlAHMAcwAgAC0AQQBjAHQAaQB2AGkAdAB5ACAAIgBEAG8AdwBuAGwAbwBhAGQAaQBuAGcAOgAgACQAKAAkAEUAdgBlAG4AdABBAHIAZwBzAC4AUAByAG8AZwByAGUAcwBzAFAAZQByAGMAZQBuAHQAYQBnAGUAKQAlACAAQwBvAG0AcABsAGUAdABlAGQAIgAgAC0AUwB0AGEAdAB1AHMAIAAkAHUAcgBsACAALQBQAGUAcgBjAGUAbgB0AEMAbwBtAHAAbABlAHQAZQAgACQARQB2AGUAbgB0AEEAcgBnAHMALgBQAHIAbwBnAHIAZQBzAHMAUABlAHIAYwBlAG4AdABhAGcAZQA7ACAAfQAgACAAIAAgAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACMAUgBlAGcAaQBzAHQAZQByAC0ATwBiAGoAZQBjAHQARQB2AGUAbgB0ACAALQBJAG4AcAB1AHQATwBiAGoAZQBjAHQAIAAkAHcAYwAgAC0ARQB2AGUAbgB0AE4AYQBtAGUAIABEAG8AdwBuAGwAbwBhAGQARgBpAGwAZQBDAG8AbQBwAGwAZQB0AGUAZAAgAC0AUwBvAHUAcgBjAGUASQBkAGUAbgB0AGkAZgBpAGUAcgAgAFcAZQBiAEMAbABpAGUAbgB0AC4ARABvAHcAbgBsAG8AYQBkAEYAaQBsAGUAQwBvAG0AcABsAGUAdABlACAALQBBAGMAdABpAG8AbgAgAHsAIABXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgBEAG8AdwBuAGwAbwBhAGQAIABDAG8AbQBwAGwAZQB0AGUAIAAtACAAJABmAGkAbABlAG4AYQBtAGUAIgA7ACAAVQBuAHIAZQBnAGkAcwB0AGUAcgAtAEUAdgBlAG4AdAAgAC0AUwBvAHUAcgBjAGUASQBkAGUAbgB0AGkAZgBpAGUAcgAgAFcAZQBiAEMAbABpAGUAbgB0AC4ARABvAHcAbgBsAG8AYQBkAFAAcgBvAGcAcgBlAHMAcwBDAGgAYQBuAGcAZQBkADsAIABVAG4AcgBlAGcAaQBzAHQAZQByAC0ARQB2AGUAbgB0ACAALQBTAG8AdQByAGMAZQBJAGQAZQBuAHQAaQBmAGkAZQByACAAVwBlAGIAQwBsAGkAZQBuAHQALgBEAG8AdwBuAGwAbwBhAGQARgBpAGwAZQBDAG8AbQBwAGwAZQB0AGUAOwAgAH0AIAAgAA0ACgANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAjACQAdwBjAC4ARABvAHcAbgBsAG8AYQBkAEYAaQBsAGUAQQBzAHkAbgBjACgAJAB1AHIAbAAsACAAJAB0AGUAYQBtAHMAZQB4AGUAKQANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAHcAYwAuAEQAbwB3AG4AbABvAGEAZABGAGkAbABlACgAJAB1AHIAbAAsACAAJAB0AGUAYQBtAHMAZQB4AGUAKQANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAfQANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAH0ADQAKAA0ACgAkAGQAbABkAGUAcwB0ACAAPQAgACgAJABoAG8AbQBlACAAKwAgACcAXABkAG8AdwBuAGwAbwBhAGQAcwBcAG0AeQB1AG4AaQBuAHMAdAAuAHoAaQBwACcAKQANAAoAJAB1AG4AegBpAHAAZABlAHMAdAAgAD0AIAAoACQAaABvAG0AZQAgACsAIAAnAFwAZABvAHcAbgBsAG8AYQBkAHMAXABtAHkAdQBuAGkAbgBzAHQAXAAnACkADQAKAA0ACgBpAGYAIAAoACAALQBOAG8AdAAgACgAdABlAHMAdAAtAHAAYQB0AGgAIAAoACQAdQBuAHoAaQBwAGQAZQBzAHQAKQApACkADQAKAHsADQAKACAAIAAgACAAJAB1AHIAbAAgAD0AIAAnAGgAdAB0AHAAcwA6AC8ALwB3AHcAdwAuAG4AaQByAHMAbwBmAHQALgBuAGUAdAAvAHUAdABpAGwAcwAvAG0AeQB1AG4AaQBuAHMAdAAuAHoAaQBwACcADQAKACAAIAAgACAAKABOAGUAdwAtAE8AYgBqAGUAYwB0ACAAUwB5AHMAdABlAG0ALgBOAGUAdAAuAFcAZQBiAEMAbABpAGUAbgB0ACkALgBEAG8AdwBuAGwAbwBhAGQARgBpAGwAZQAoACAAJAB1AHIAbAAgACwAJABkAGwAZABlAHMAdAApAA0ACgAgACAAIAAgAEUAeABwAGEAbgBkAC0AQQByAGMAaABpAHYAZQAgAC0AUABhAHQAaAAgACQAZABsAGQAZQBzAHQAIAAtAEQAZQBzAHQAaQBuAGEAdABpAG8AbgBQAGEAdABoACAAJAB1AG4AegBpAHAAZABlAHMAdAANAAoAfQANAAoADQAKACMAUwB0AGEAcgB0AC0AUAByAG8AYwBlAHMAcwAgACQAdQBuAHoAaQBwAGQAZQBzAHQADQAKAA0ACgAkAGMAbQBkACAAPQAgACgAJAB1AG4AegBpAHAAZABlAHMAdAAgACsAIAAnAG0AeQB1AG4AaQBuAHMAdAAuAGUAeABlACAALwB1AG4AaQBuAHMAdABhAGwAbAAgACIATQBpAGMAcgBvAHMAbwBmAHQAIABUAGUAYQBtAHMAIgAnACkADQAKACMAUwB0AGEAcgB0AC0AUAByAG8AYwBlAHMAcwAgACcAYwBtAGQAJwAgAC0AQQByAGcAdQBtAGUAbgB0AEwAaQBzAHQAIAAiAC8AYwAgACQAYwBtAGQAIgANAAoAUwB0AGEAcgB0AC0AUAByAG8AYwBlAHMAcwAgACgAJAB1AG4AegBpAHAAZABlAHMAdAAgACsAIAAnAG0AeQB1AG4AaQBuAHMAdAAuAGUAeABlACcAKQAgAC0AQQByAGcAdQBtAGUAbgB0AEwAaQBzAHQAIAAnAC8AdQBuAGkAbgBzAHQAYQBsAGwAIAAiAE0AaQBjAHIAbwBzAG8AZgB0ACAAVABlAGEAbQBzACIAJwANAAoADQAKACQAdABpAG0AZQAgAD0AIAAwAA0ACgBkAG8AewANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAjACQAUgBlAHMAdQBsAHQAIAA9ACAAZwBlAHQALQBqAG8AYgAgAC0ATgBhAG0AZQAgAGQAbAB0AGUAYQBtAHMAIAAgACAAIwB8ACAAdwBoAGUAcgBlACAAcwB0AGEAdABlACAALQBlAHEAIABDAG8AbQBwAGwAZQB0AGUAZAAgAHwAIABSAGUAYwBlAGkAdgBlAC0AagBvAGIADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACMAJABSAGUAcwB1AGwAdAAgACMALgBPAG4AbABpAG4AZQANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAVwByAGkAdABlAC0ASABvAHMAdAAoACgARwBlAHQALQBJAHQAZQBtACAAJAB0AGUAYQBtAHMAZQB4AGUAKQAuAGwAZQBuAGcAdABoAC8AMQBNAEIAKQAgAE0AQgANAAoADQAKAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAHQAaQBtAGUAKwArAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIABzAGwAZQBlAHAAIAAtAFMAZQBjAG8AbgBkAHMAIAAxAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAB3AHIAaQB0AGUALQBoAG8AcwB0ACAAdwBhAGkAdAAgAGYAbwByACAAZABsAHQAZQBhAG0AcwAgAHQAbwAgAGYAaQBuAGkAcwBoACAAJAB0AGkAbQBlACAAcwBlAGMAIABlAGwAYQBwAHMAZQBkACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAA0ACgAgAH0ADQAKACAAdwBoAGkAbABlACgAKABHAGUAdAAtAGoAbwBiACAALQBOAGEAbQBlACAAZABsAHQAZQBhAG0AcwAgAHwAIAB3AGgAZQByAGUAIABzAHQAYQB0AGUAIAAtAGUAcQAgAFIAdQBuAG4AaQBuAGcAKQAgAC0AYQBuAGQAIAAoACQAVABpAG0AZQAgAC0AbAB0ACAAMQAyADAAKQApAA0ACgANAAoAdwByAGkAdABlAC0AaABvAHMAdAAgAHcAYQBpAHQAIABmAG8AcgAgAEQATAAgAHQAbwAgAGYAaQBuAGkAcwBoAA0ACgBHAGUAdAAtAEoAbwBiACAAIAAtAE4AYQBtAGUAIABkAGwAdABlAGEAbQBzACAAfAAgAFcAYQBpAHQALQBKAG8AYgANAAoADQAKAA0ACgAkAGMAbQBkACAAPQAgACgAJABoAG8AbQBlACAAKwAgACcAXABkAG8AdwBuAGwAbwBhAGQAcwBcAFQAZQBhAG0AcwBfAHcAaQBuAGQAbwB3AHMAXwB4ADYANAAuAGUAeABlACcAKQANAAoAIwBTAHQAYQByAHQALQBQAHIAbwBjAGUAcwBzACAAJwBjAG0AZAAnACAALQBBAHIAZwB1AG0AZQBuAHQATABpAHMAdAAgACIALwBjACAAJABjAG0AZAAiAA0ACgBTAHQAYQByAHQALQBQAHIAbwBjAGUAcwBzACAAKAAkAGgAbwBtAGUAIAArACAAJwBcAGQAbwB3AG4AbABvAGEAZABzAFwAVABlAGEAbQBzAF8AdwBpAG4AZABvAHcAcwBfAHgANgA0AC4AZQB4AGUAJwApAA0ACgANAAoA
